### ISSUE TITLE
Wrongly formatted CSV files create an exception

### ISSUE THREAD

**Issue by glatard** [aces/cbrain-plugins-neuro#26]
```
Exception: ScriptError: Coding error: method before_form() for CbrainTask::FslMelodic raised an exception: CSV::MalformedCSVError: Unquoted fields do not allow \r or \n (line 5).

/home/cbrainsys/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/csv.rb:1871:in `block (2 levels) in shift'
/home/cbrainsys/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/csv.rb:1836:in `each'
/home/cbrainsys/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/csv.rb:1836:in `block in shift'
/home/cbrainsys/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/csv.rb:1796:in `loop'
/home/cbrainsys/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/csv.rb:1796:in `shift'
/home/cbrainsys/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/csv.rb:1738:in `each'
/home/cbrainsys/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/csv.rb:1752:in `to_a'
/home/cbrainsys/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/csv.rb:1752:in `read'
/home/cbrainsys/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/csv.rb:1298:in `parse'
/home/cbrainsys/DEV_CBRAIN/BrainPortal/cbrain_plugins/installed-plugins/userfiles/csv_file/csv_file.rb:170:in `parse_file_content_as_csv'
/home/cbrainsys/DEV_CBRAIN/BrainPortal/cbrain_plugins/installed-plugins/userfiles/csv_file/csv_file.rb:156:in `create_csv_array'
/home/cbrainsys/DEV_CBRAIN/BrainPortal/cbrain_plugins/installed-plugins/cbrain_task/fsl_melodic/portal/fsl_melodic.rb:129:in `parse_csv_file'
/home/cbrainsys/DEV_CBRAIN/BrainPortal/cbrain_plugins/installed-plugins/cbrain_task/fsl_melodic/portal/fsl_melodic.rb:55:in `before_form'
/home/cbrainsys/DEV_CBRAIN/BrainPortal/app/models/portal_task.rb:359:in `wrapper_before_form'
/home/cbrainsys/DEV_CBRAIN/BrainPortal/app/controllers/tasks_controller.rb:225:in `new'
/home/cbrainsys/.rvm/gems/ruby-2.2.0/bundler/gems/rails-3b4398bb605c/actionpack/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/home/cbrainsys/.rvm/gems/ruby-2.2.0/bundler/gems/rails-3b4398bb605c/actionpack/lib/abstract_controller/base.rb:167:in `process_action'
/home/cbrainsys/.rvm/gems/ruby-2.2.0/bundler/gems/rails-3b4398bb605c/actionpack/lib/action_controller/metal/rendering.rb:10:in `process_action'
/home/cbrainsys/.rvm/gems/ruby-2.2.0/bundler/gems/rails-3b4398bb605c/actionpack/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
/home/cbrainsys/.rvm/gems/ruby-2.2.0/bundler/gems/rails-3b4398bb605c/activesupport/lib/active_support/callbacks.rb:525:in `block in _run__3217895913174204533__process_action__1227200730664726714__callbacks'
/home/cbrainsys/.rvm/gems/ruby-2.2.0/bundler/gems/rails-3b4398bb605c/activesupport/lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_1038'
/home/cbrainsys/DEV_CBRAIN/BrainPortal/app/controllers/application_controller.rb:101:in `activate_user_time_zone'
/home/cbrainsys/.rvm/gems/ruby-2.2.0/bundler/gems/rails-3b4398bb605c/activesupport/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_1038'
/home/cbrainsys/.rvm/gems/ruby-2.2.0/bundler/gems/rails-3b4398bb605c/activesupport/lib/active_support/callbacks.rb:513:in `_run__3217895913174204533__process_action__1227200730664726714__callbacks'
/home/cbrainsys/.rvm/gems/ruby-2.2.0/bundler/gems/rails-3b4398bb605c/activesupport/lib/active_support/callbacks.rb:405:in `__run_callback'
/home/cbrainsys/.rvm/gems/ruby-2.2.0/bundler/gems/rails-3b4398bb605c/activesupport/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
/home/cbrainsys/.rvm/gems/ruby-2.2.0/bundler/gems/rails-3b4398bb605c/activesupport/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/cbrainsys/.rvm/gems/ruby-2.2.0/bundler/gems/rails-3b4398bb605c/actionpack/lib/abstract_controller/callbacks.rb:17:in `process_action'
/home/cbrainsys/.rvm/gems/ruby-2.2.0/bundler/gems/rails-3b4398bb605c/actionpack/lib/action_controller/metal/rescue.rb:29:in `process_action'
/home/cbrainsys/.rvm/gems/ruby-2.2.0/bundler/gems/rails-3b4398bb605c/actionpack/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
/home/cbrainsys/.rvm/gems/ruby-2.2.0/bundler/gems/rails-3b4398bb605c/activesupport/lib/active_support/notifications.rb:123:in `block in instrument'
```

**Comment by glatard** [comment]
Asked the user for the problematic CSV file. Couldn't reproduce the bug (exception was raised in method create_csv_array of csv_file.rb).  So, in fsl_melodic.rb, rescued any exception coming from this method and reported error message.
